### ISSUE TITLE
does routing with live speed work?

### ISSUE THREAD

**Issue by adrius531** [alinmindroc/valhalla_traffic_poc#10]
Hi,
I've generated the traffic.tar with live speeds. The calculated route seems to use always the same route (curl http://localhost:8002/route, costing auto) although the live speeds are set to a very low speed (1 km/h) on multiple edges along the original route. When I use curl http://localhost:8002/locate to check the live speed on an edge, the live speed is correctly set. The route is with 3 km pretty short, but I think even then it should give an alternative route.

Best regards
Adrian

**Comment by alinmindroc** [comment]
Hello,
Yes, routing with live speeds should work. Check the section in the readme, you should use time dependent routing, which adds an extra parameter to the route call: https://github.com/bolteu/bolt-server/pull/63136

**Comment by adrius531** [comment]
Hi,
thank you very much, that helped a lot. I thought the date_time was only relevant for predicted traffic.
Best regards
