### ISSUE TITLE
GetSpeed example

### ISSUE THREAD

**Issue by coderon98** [alinmindroc/valhalla_traffic_poc#13]
Hi, first of all congratulations on the quality of your work.
You mentioned the use of GetSpeed in your readMe.md.
Is it possible to retrieve the configured speed from an edge id? 

Thanks

**Comment by alinmindroc** [comment]
Hello,

Sure, there is no support for this as it was outside the scope of this demo, but the speeds are saved in a tar file for live traffic an under a hierarchy of directories in csv files for predicted traffic. 

So you will need to create a new binary that reads from these files, starting from the existing code in `valhalla_traffic_demo_utils.cc`. 
Try to understand how all the steps in the dockerfile of this project work together, it is a simple flow and well documented. Then it should become more clear how to read the configured speeds.

**Comment by coderon98** [comment]
Thank you so much
