### ISSUE TITLE
can realtime traffic be taken into account without restarting the service?

### ISSUE THREAD

**Issue by xlqian** [alinmindroc/valhalla_traffic_poc#17]
As indicated in the title, can real-time traffic be taken into account without restarting the service? 

It seems in this demo, I have to restart the service to update the traffic, right? 

otherwise, does some more heavy work need to be done as explained [here](https://github.com/valhalla/valhalla/issues/3414#issuecomment-974310669) to achieve that? 

thank you

**Comment by alinmindroc** [comment]
Hello,

Yes, traffic can be updated without restarting the service. The `valhalla_traffic_demo_utils` tool that is implemented as part of this repo is the _external process which writes directly into the tar_ from the post that you linked. 

In step 6 of the readme there is a mention about restarting the service only the first time before applying traffic. But basically afterwards you can use `valhalla_traffic_demo_utils` as many times as you want and the traffic will be updated.

**Comment by xlqian** [comment]
wonderful! thank you
