### ISSUE TITLE
Injecting Here maps traffic data

### ISSUE THREAD

**Issue by jiruhameru** [alinmindroc/valhalla_traffic_poc#4]
Would you be able to inject separate Here maps traffic data files in TMC/DATEX II format?

Thanks in advance for your answer.

**Comment by mindrocalin** [comment]
Hello,

Nope, I'm afraid that's not in my plans. The idea of this repo is to show a basic way in which you can get predicted or live traffic working with Valhalla, so feel free to fork the repo and adjust it for your needs.

You can try asking in a Valhalla discussion if someone else has experience with here maps traffic: https://github.com/valhalla/valhalla/discussions

**Comment by jiruhameru** [comment]
Thanks. Will do.
